### ISSUE TITLE
Colab does not work anymore?

### ISSUE THREAD

**Issue by Taikakim** [Music-and-Culture-Technology-Lab/omnizart#87] opened 2023-01-18 11:13 UTC
I'm getting this when trying to run the drum transcription. On the first run it was actually something else, but I restarted the runtime and ran everything again, and got this now.
```

---------------------------------------------------------------------------

RuntimeError                              Traceback (most recent call last)

RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd

---------------------------------------------------------------------------

ImportError                               Traceback (most recent call last)

[<ipython-input-2-2fb5724a6242>](https://localhost:8080/#) in <module>
     11 
     12 from omnizart.music import app as mapp
---> 13 from omnizart.chord import app as capp
     14 from omnizart.drum import app as dapp
     15 from omnizart.vocal import app as vapp

3 frames

[/usr/local/lib/python3.8/dist-packages/vamp/__init__.py](https://localhost:8080/#) in <module>
    161 '''
    162 
--> 163 import vampyhost
    164 
    165 from vamp.load import list_plugins, get_outputs_of, get_category_of

ImportError: numpy.core.multiarray failed to import


---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
---------------------------------------------------------------------------
```

**Comment by BreezeWhite** [comment] 2023-02-15 04:31
Sorry but I could not reproduce the error. Try reinstall numpy with `pip uninstall numpy` then `pip install numpy`.

**Comment by sam-evans** [comment] 2023-03-13 22:15
> Sorry but I could not reproduce the error. Try reinstall numpy with `pip uninstall numpy` then `pip install numpy`.

After re-installing numpy, collab still doesn't work. What version of numpy do you have installed to run the transcription?

**Comment by BreezeWhite** [comment] 2024-03-10 04:51
The issue should be fixed now.

**Closed by BreezeWhite** 2024-03-10 04:51 UTC
Labels: colab

**Comment by Taikakim** [comment] 2024-03-27 07:10
Fabulous! There's not too many good audio to MIDI solutions around so this definitely has it's place.
